### ISSUE TITLE
TP3

### ISSUE THREAD

**Issue by Francisco004** [Francisco004/TP_SO_i3_Equipo_3#1]

**Comment by Francisco004** [comment]
Hola, falta santiago para hacer el paso 3

**Comment by Francisco004** [comment]
tenes idea como bajo el repositorio con tu rama ? por que me baja el repositorio pero solo con lo que subi yo

**Comment by patricioeyjo** [comment]
ni idea, creo que tenes que bajarlo y cambiar de rama con git checkout
